#ifndef REMOTECONTROLLER_CONFIG_H_
#define REMOTECONTROLLER_CONFIG_H_

#if !defined(REMOTECONTROLLER_CUSTOM_CONFIG)

#define REMOTECONTROLLER_INCOMING_BUFFER_SIZE 32 // bytes
#define REMOTECONTROLLER_OUTGOING_BUFFER_SIZE 32 // bytes
#define REMOTECONTROLLER_COMMAND_QUEUE_SIZE 50 // bytes (Allows for 10 commands to be in the queue at once)
#define REMOTECONTROLLER_ENCODED_COMMAND_SIZE 5 // 1 byte intruction and 4 byte float throttle as specified in RemoteController-Protocol
#define REMOTECONTROLLER_INCOMING_CALLBACK_ARRAY_LENGTH (REMOTECONTROLLER_INCOMING_BUFFER_SIZE - 2) / REMOTECONTROLLER_ENCODED_COMMAND_SIZE

#define REMOTECONTROLLER_IDENTIFIER_COMMAND 0xEEAF // RemoteController Identifier 2 bytes

#endif


#endif